font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size 11.0
disable_ligatures never

cursor_shape beam
cursor_blink_interval 0

window_padding_width 14
hide_window_decorations yes
confirm_os_window_close 0
enable_audio_bell no
visual_bell_duration 0

background_opacity 1.0
dynamic_background_opacity no

# Monochrome + sparse amber
foreground              #f2f2f2
background              #0e0e10
selection_foreground    #0e0e10
selection_background    #c8c8c8
cursor                  #e0c373
cursor_text_color       #0e0e10

url_color               #e0c373
active_border_color     #c8c8c8
inactive_border_color   #2e2e34
bell_border_color       #b56565

active_tab_foreground   #0e0e10
active_tab_background   #e0c373
inactive_tab_foreground #909094
inactive_tab_background #1a1a1d

color0  #1a1a1d
color1  #b56565
color2  #c8c8c8
color3  #e0c373
color4  #c8c8c8
color5  #c8c8c8
color6  #c8c8c8
color7  #f2f2f2
color8  #5e5e62
color9  #b56565
color10 #f2f2f2
color11 #e0c373
color12 #f2f2f2
color13 #f2f2f2
color14 #f2f2f2
color15 #ffffff
